// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Transaction struct {
	ID          pgtype.UUID
	FromUserID  pgtype.UUID
	ToUserID    pgtype.UUID
	Date        pgtype.Timestamp
	Amount      int64
	Description pgtype.Text
}

type User struct {
	ID       pgtype.UUID
	Username string
	Email    string
	Password string
	Balance  int64
}
